In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import joblib

In [2]:
constant = np.random.randint(0,5,50)

In [3]:
x = np.random.randint(0,10,50)
y = constant + 3 * x

In [4]:
y

array([20, 29, 16, 11,  9, 10,  7, 27, 22, 10, 28, 12,  4, 14, 31,  7,  0,
        3,  9,  0, 18,  9,  4, 15,  9, 13,  2,  3, 28,  7, 23, 28, 16, 28,
       30,  0, 10, 22, 22, 21, 19, 14, 18, 13, 24,  6, 13,  6, 29,  6])

In [5]:
x

array([6, 9, 4, 3, 2, 2, 1, 8, 6, 3, 9, 3, 1, 4, 9, 2, 0, 1, 2, 0, 6, 2,
       0, 4, 3, 3, 0, 0, 8, 1, 7, 8, 5, 8, 9, 0, 2, 7, 7, 6, 5, 4, 5, 4,
       8, 2, 4, 1, 9, 1])

In [6]:
constant

array([2, 2, 4, 2, 3, 4, 4, 3, 4, 1, 1, 3, 1, 2, 4, 1, 0, 0, 3, 0, 0, 3,
       4, 3, 0, 4, 2, 3, 4, 4, 2, 4, 1, 4, 3, 0, 4, 1, 1, 3, 4, 2, 3, 1,
       0, 0, 1, 3, 2, 3])

In [7]:
df = pd.DataFrame({"x":x, "y":y})
df.sample(5)

x   y
4   2   9
14  9  31
40  5  19
10  9  28
34  9  30

In [8]:
model = LinearRegression()
model.fit(x.reshape(-1,1),y)

LinearRegression()

In [9]:
model.coef_

array([3.05063641])

In [10]:
joblib.dump(model,"my_model")

['my_model']

In [11]:
model.predict([[10]])

array([32.55976757])

In [12]:
%pip install fastapi

Note: you may need to restart the kernel to use updated packages.


Dosya ad�, dizin ad� veya birim etiketi s�zdizimi hatal�.


ModuleNotFoundError: No module named 'fastapi'